# Generated by Django 4.1.7 on 2023-03-07 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True)),
                ('update_time', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cars',
                                           to='user.usermodel')),
            ],
            options={
                'verbose_name': 'cars',
                'verbose_name_plural': 'cars',
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarsCommodityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars',
                                           to='cars.carsmodel')),
                ('commodity',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_commodity',
                                   to='commodity.commoditymodel')),
            ],
            options={
                'verbose_name': 'car_commodity',
                'verbose_name_plural': 'car_commodity',
                'db_table': 'car_commodity',
            },
        ),
    ]
