# Generated by Django 4.1.7 on 2023-03-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True)),
                ('update_time', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
