# Generated by Django 4.1.7 on 2023-03-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True)),
                ('update_time', models.DateField(auto_now_add=True)),
                ('commodity_name', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('classify', models.SmallIntegerField(
                    choices=[(1, '女装'), (2, '男装'), (3, '母婴用品'), (4, '鞋类箱包'), (5, '护肤彩妆'), (6, '美食'), (7, '珠宝配饰'),
                             (8, '家装建材'), (9, '百货市场')])),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_grounding', models.BooleanField()),
            ],
            options={
                'verbose_name': 'commodity',
                'verbose_name_plural': 'commodity',
                'db_table': 'commodity',
            },
        ),
    ]
