# Generated by Django 4.1.7 on 2023-03-07 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True)),
                ('update_time', models.DateField(auto_now_add=True)),
                ('money', models.IntegerField()),
                ('is_delete', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order',
                                              to='user.usermodel')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderCommodityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('commodity',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_commodities',
                                   to='commodity.commoditymodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order',
                                            to='order.ordermodel')),
            ],
            options={
                'verbose_name': 'order_commodity',
                'verbose_name_plural': 'order_commodity',
                'db_table': 'order_commodity',
            },
        ),
    ]
